### PR TITLE
Go templates support, XML, JSON, Ingress

### PR DESCRIPTION
**Pull request by tarampampam**
### Changed

- It is now possible to use [golang-tags of templates](https://pkg.go.dev/text/template) in error page templates and formatted (`json`, `xml`) responses
- Health-check route become `/healthz` (instead `/health/live`, previous route marked ad deprecated)

### Added

- The templates contain details block now (can be enabled using `--show-details` flag for the `serve` command or environment variable `SHOW_DETAILS=true`)
- Formatted response templates (`json`, `xml`) - the server responds with a formatted response depending on the `Content-Type` (and `X-Format`) request header value
- HTTP header `X-Robots-Tag: noindex` for the error pages
- Possibility to pass the needed error page code using `X-Code` HTTP header
- Possibility to integrate with [ingress-nginx](https://kubernetes.github.io/ingress-nginx/)

### Fixed

- Potential race condition (in the `pick.StringsSlice` struct)

Related issue #45

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by onedr0p** [comment]
w00t, that's a lot of changes. In the interest of testing I see there was no docker image pushed anywhere. Any chance to update the pipeline to maybe push PRs as `:sha` or something else you are more comfortable with?

**Comment by tarampampam** [comment]
@onedr0p ez! [tarampampam/error-pages:ingress-test](https://hub.docker.com/layers/tarampampam/error-pages/ingress-test/images/sha256-b877c2d074dc4ab2b82e1ff6ee60e31191e77b0edbf0a7c7054e8cb032c3a730?context=explore)

**Comment by onedr0p** [comment]
Almost, the ingress-nginx `defaultBackend` expects a `/healthz` as a healthcheck endpoint. I do not see a way to change that in the helm chart. It is hardcoded:

https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/default-backend-deployment.yaml#L76

Would that be okay to add?

**Comment by tarampampam** [comment]
Yes, sure, I will add additional route for the healthcheck. Tomorrow

**Comment by tarampampam** [comment]
@onedr0p updated!

**Comment by tarampampam** [comment]
@onedr0p I updated the image (`tarampampam/error-pages:ingress-test`) again - please check, I am waiting for your feedback

**Pull request merged**
