### PR TITLE
Update 100-setup-error-pages.sh

### PR DESCRIPTION
**Pull request by xpliz**
## Description

Random template generator, also picked up nginx-error-pages template, which we don't want. Proposing small patch to exclude from allowed_templates

### CODE REVIEW

**Comment by tarampampam** [comment]
:+1: Great thanks for your contribution!

**Comment by xpliz** [comment]
Did I mess up this patch? Can't find it in code.

**Comment by tarampampam** [comment]
@xpliz You closed this PR before I merge it. Also, can you say how to reproduce the fixed error?

**Comment by tarampampam** [comment]
Thanks for the detailed response! I have made other changes, could you approve them?

**Comment by xpliz** [comment]
This github baffles me :)

**Comment by xpliz** [comment]
I can't seem to find approve or merge lol :)

**Comment by tarampampam** [comment]
Released in https://github.com/tarampampam/error-pages/releases/tag/v1.7.1

**Pull request merged**
