### PR TITLE
Add 🇨🇳 Chinese Translation

### PR DESCRIPTION
**Pull request by CDN18**
## Description

Adding 🇨🇳 translation.

Update: Sorry I typed wrong PR id and link (should be #147, I typed #145)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests are required for my changes)_ 
- [x] I have made changes in the `CHANGELOG.md` file

### CODE REVIEW

**Comment by tarampampam** [comment]
Please, revert change log file changes

**Comment by CDN18** [comment]
> Please, revert the markdown files changes

Ok, already reverted

**Comment by tarampampam** [comment]
You've done a tremendous job! Thank you!

**Comment by tarampampam** [comment]
Released in [v2.19.0](https://github.com/tarampampam/error-pages/releases/tag/v2.19.0)

**Pull request merged**
