### PR TITLE
Fix translation 🇫🇷

### PR DESCRIPTION
**Pull request by jvin042**
## Description

# Fixed

Fix translation 🇫🇷

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by tarampampam** [comment]
Dots at the end of strings are really needed?

**Comment by jvin042** [comment]
Yes, in French punctuation, phrases end with dots.

**Comment by tarampampam** [comment]
Yeah, I think we should ignore them here... But another modifications looks very nice!

**Comment by jvin042** [comment]
I'l push request to you again in about 30 minutes 🙂

**Pull request closed without merging**
