### PR TITLE
Error pages now translated in 🇫🇷

### PR DESCRIPTION
**Pull request by jvin042**
## Description

# Changed
- Error pages now translated in 🇫🇷

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Review by tarampampam — APPROVED** [review]
You've done a tremendous job! Thank you!

**Comment by tarampampam** [comment]
@jvin042 [v2.12.0 released](https://github.com/tarampampam/error-pages/releases/tag/v2.12.0)! Please, check on your side after a few minutes (when the CI process is completed)

**Comment by jvin042** [comment]
@tarampampam idiot question, how do you put the language ? I did not find. I'm use docker-compose and traefik.

**Comment by tarampampam** [comment]
@jvin042 this is a normal question :) The details are described here:

https://github.com/tarampampam/error-pages/blob/873944f90f4597b3c325e51301e00986bde4cd5c/l10n/readme.md?plain=1#L5

Also, each template loads `l10n.js` file like this:

https://github.com/tarampampam/error-pages/blob/873944f90f4597b3c325e51301e00986bde4cd5c/templates/matrix.html#L265-L272

So, if your browser locale `!== 'en'` - the script will localize all required messages automatically.

Opened question is a cache lifetine on the jsdelivr side (I have found [this explanation](https://github.com/jsdelivr/jsdelivr#caching=) about the caching strategy) - I am currently looking for ways to clear the cache manually.

**Comment by tarampampam** [comment]
https://cdn.jsdelivr.net/gh/tarampampam/error-pages@2/l10n/l10n.min.js at this moment contains outdated content (without the `fr` locale) - I am currently looking for ways to reset the cache manually

**Comment by tarampampam** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/tarampampam/error-pages@2/l10n/l10n.min.js

**Comment by tarampampam** [comment]
Automatic cache refreshing can takes about 12 hours. So, we can only have one option for now - wait for tomorrow ;)

**Comment by jvin042** [comment]
Yes it is :) Thanks you :)

image

**Comment by tarampampam** [comment]
I have found the solution. Please, purge the cache in your browser and try again:

```bash
curl -s https://cdn.jsdelivr.net/gh/tarampampam/error-pages@2/l10n/l10n.min.js | head -c 499
/**
 * Minified by jsDelivr using Terser v5.10.0.
 * Original file: /gh/tarampampam/error-pages@2.12.0/l10n/l10n.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
Object.defineProperty(window,"l10n",{value:new function(){const e={Error:{fr:"Erreur",ru:"Ошибка",uk:"Помилка"},"Good luck":{fr:"Bonne chance",ru:"Удачи",uk:"Успіхів"},"UH OH":{fr:"Oups",ru:"Ох",uk:"Ох"},"Request details":{
```

**Comment by jvin042** [comment]
@tarampampam I confirm that it works ! 😉

**Pull request merged**
